services:
  - type: static
    name: os-portfolio
    env: static
    buildCommand: npm run build
    staticPublishDir: dist
    autoDeploy: true
    headers:
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: same-origin
      - path: /*
        name: Cross-Origin-Embedder-Policy
        value: credentialless
      - path: /*
        name: Cross-Origin-Resource-Policy
        value: cross-origin

  - type: web
    name: y-webrtc-signaling
    env: node
    buildCommand: npm install
    startCommand: npx y-webrtc-signaling --port 10000
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: 10000

